[tool.poetry]
name = "pki-chain-builder"
version = "1.0.0"
description = "PKI Chain Builder"
authors = ["Bakminstof <bakminstof@yandex.ru>"]
readme = "README.md"
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.12"
cryptography = "^45.0.6"
bottle = "^0.13.4"
pydantic = "^2.11.7"
pydantic-settings = "^2.10.1"
rich = "^14.1.0"
rich-argparse = "^1.7.1"
logging-settings = "^0.1.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
